stages:
  preprocessing:
    cmd: python src/data/1_Datasplit.py
    deps:
    - data/raw_data
    - src/data/1_Datasplit.py
    outs:
    - data/processed_data
  preprocessing2:
    cmd: python src/data/2_Standardization.py
    deps:
    - data/processed_data
    - src/data/2_Standardization.py
    outs:
    - data/standardization
  Gridsearch:
    cmd: python src/models/3_Gridsearch.py
    deps:
    - data/processed_data
    - data/standardization
    - src/models/3_Gridsearch.py
    outs:
    - models/gradient_boosting_best_params.pkl
